apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-volume
spec:
  storageClassName: rook-cephfs-central
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "250Mi"
