apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-volume
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "250Mi"
